# Generated by Django 4.2.2 on 2023-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_customuser_altura_alter_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='peso',
            field=models.FloatField(blank=True, max_length=4),
        ),
    ]
