# Generated by Django 4.2.2 on 2023-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_customuser_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='peso',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
    ]
