# Generated by Django 4.2.2 on 2023-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_customuser_altura_alter_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='altura',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='peso',
            field=models.FloatField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
