# Generated by Django 4.2.2 on 2023-08-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjerciciosDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunes', models.JSONField(default=list)),
                ('Martes', models.JSONField(default=list)),
                ('Miercoles', models.JSONField(default=list)),
                ('Jueves', models.JSONField(default=list)),
                ('Viernes', models.JSONField(default=list)),
                ('Sabado', models.JSONField(default=list)),
                ('Domingo', models.JSONField(default=list)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
